# Add your discord bot token below, between the quotation marks
# Find the token of your bot on https://discord.com/developers/applications/me
# Tutorial: https://github.com/reactiflux/discord-irc/wiki/Creating-a-discord-bot-&-getting-a-token
discordToken: "ODg5OTcxMDY5OTM3NjgwNDE0.YUpAJQ.1UxNVypTV4LRwYoZ1s_VYEZcOu8"